---
env:
  es2020: true
parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'
  tsConfigRootDir: '__dirname'
  ecmaFeatures:
    jsx: true
plugins:
  - 'react'
  - '@typescript-eslint'
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:react/recommended'
  - 'next/core-web-vitals'
  - 'prettier'
rules:
  '@next/next/no-img-element': off
settings:
  react:
    version: 'detect'
